trigger: none 

pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'

stages:
- template: semver-increment-check.yml@templates