/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ToastNotificationOptions } from "../../../src/components/shared/elsa-toast-notification/elsa-toast-notification";
import { MonacoValueChangedArgs } from "../../src/components/editors/he-monaco/he-monaco";
export { ToastNotificationOptions } from "../../../src/components/shared/elsa-toast-notification/elsa-toast-notification";
export { MonacoValueChangedArgs } from "../../src/components/editors/he-monaco/he-monaco";
export namespace Components {
    interface ElsaToastNotification {
        "hide": () => Promise<void>;
        "show": (options: ToastNotificationOptions) => Promise<void>;
    }
    interface HeMonaco {
        "addJavaScriptLib": (libSource: string, libUri: string) => Promise<void>;
        /**
          * @default '5em'
         */
        "editorHeight": string;
        "language": string;
        "monacoLibPath": string;
        "padding": string;
        "setValue": (value: string) => Promise<void>;
        /**
          * @default false
         */
        "singleLineMode": boolean;
        "value": string;
    }
}
export interface HeMonacoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeMonacoElement;
}
declare global {
    interface HTMLElsaToastNotificationElement extends Components.ElsaToastNotification, HTMLStencilElement {
    }
    var HTMLElsaToastNotificationElement: {
        prototype: HTMLElsaToastNotificationElement;
        new (): HTMLElsaToastNotificationElement;
    };
    interface HTMLHeMonacoElementEventMap {
        "valueChanged": MonacoValueChangedArgs;
    }
    interface HTMLHeMonacoElement extends Components.HeMonaco, HTMLStencilElement {
        addEventListener<K extends keyof HTMLHeMonacoElementEventMap>(type: K, listener: (this: HTMLHeMonacoElement, ev: HeMonacoCustomEvent<HTMLHeMonacoElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLHeMonacoElementEventMap>(type: K, listener: (this: HTMLHeMonacoElement, ev: HeMonacoCustomEvent<HTMLHeMonacoElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLHeMonacoElement: {
        prototype: HTMLHeMonacoElement;
        new (): HTMLHeMonacoElement;
    };
    interface HTMLElementTagNameMap {
        "elsa-toast-notification": HTMLElsaToastNotificationElement;
        "he-monaco": HTMLHeMonacoElement;
    }
}
declare namespace LocalJSX {
    interface ElsaToastNotification {
    }
    interface HeMonaco {
        /**
          * @default '5em'
         */
        "editorHeight"?: string;
        "language"?: string;
        "monacoLibPath"?: string;
        "onValueChanged"?: (event: HeMonacoCustomEvent<MonacoValueChangedArgs>) => void;
        "padding"?: string;
        /**
          * @default false
         */
        "singleLineMode"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "elsa-toast-notification": ElsaToastNotification;
        "he-monaco": HeMonaco;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elsa-toast-notification": LocalJSX.ElsaToastNotification & JSXBase.HTMLAttributes<HTMLElsaToastNotificationElement>;
            "he-monaco": LocalJSX.HeMonaco & JSXBase.HTMLAttributes<HTMLHeMonacoElement>;
        }
    }
}
