trigger:
  branches:
    include:
    - '*'

variables:
  tag: '$(Build.BuildId)'

resources:
  repositories:
    - repository: templates
      type: git
      name: 'Cloud Hosting Service/Templates'    

pool:
  vmImage: 'ubuntu-18.04'

# Build
stages:
- stage: build
  displayName: Build
  jobs: 
    - template: dotnet.yml@templates
      parameters:
        identifier: 'he_pipeline_assessment'
        workingDirectory: 'src'
        packageVersion: $(Build.BuildNumber)
        publishOutputPath: '$(System.DefaultWorkingDirectory)/published'
        dotnetVersion: '6.0.x'
        unitTestProjects: '**/*.Tests.csproj'
        coverageThreshold: 0