# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main

schedules:
- cron: "15 3 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Nightly Test Run
  branches:
    include:
    - main
  always: true

parameters:
  - name: forcePushToProd
    displayName: Force Push to Production
    type: boolean
    default: false

variables:
  buildMajor: 1
  buildMinor: 7
  buildPatch: 9
  buildBranch: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '.')]
  identifier: pipasmt

pool: 'vmss-ado-chs-nonprod-001'

name: $(buildMajor).$(buildMinor).$(buildPatch)-$(Rev:r)-$(identifier).$(buildBranch)

resources:
  repositories:
  - repository: pipeline-assessment-deployment
    type: git
    name: 'Pipeline Assessment/pipeline-assessment-deployment'   
    ref: 'main'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'

stages:
- template: pipelines/build.yml@pipeline-assessment-deployment
  parameters:
    forcePushToProd: ${{ parameters.forcePushToProd }}
    identifier: $(identifier)