/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActivityDefinitionProperty, ActivityModel, ActivityPropertyDescriptor } from "./models/elsa-interfaces";
export namespace Components {
    interface ElsaMultichoiceRecordsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface ElsaSinglechoiceRecordsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
}
declare global {
    interface HTMLElsaMultichoiceRecordsPropertyElement extends Components.ElsaMultichoiceRecordsProperty, HTMLStencilElement {
    }
    var HTMLElsaMultichoiceRecordsPropertyElement: {
        prototype: HTMLElsaMultichoiceRecordsPropertyElement;
        new (): HTMLElsaMultichoiceRecordsPropertyElement;
    };
    interface HTMLElsaSinglechoiceRecordsPropertyElement extends Components.ElsaSinglechoiceRecordsProperty, HTMLStencilElement {
    }
    var HTMLElsaSinglechoiceRecordsPropertyElement: {
        prototype: HTMLElsaSinglechoiceRecordsPropertyElement;
        new (): HTMLElsaSinglechoiceRecordsPropertyElement;
    };
    interface HTMLElementTagNameMap {
        "elsa-multichoice-records-property": HTMLElsaMultichoiceRecordsPropertyElement;
        "elsa-singlechoice-records-property": HTMLElsaSinglechoiceRecordsPropertyElement;
    }
}
declare namespace LocalJSX {
    interface ElsaMultichoiceRecordsProperty {
        "activityModel"?: ActivityModel;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface ElsaSinglechoiceRecordsProperty {
        "activityModel"?: ActivityModel;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface IntrinsicElements {
        "elsa-multichoice-records-property": ElsaMultichoiceRecordsProperty;
        "elsa-singlechoice-records-property": ElsaSinglechoiceRecordsProperty;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elsa-multichoice-records-property": LocalJSX.ElsaMultichoiceRecordsProperty & JSXBase.HTMLAttributes<HTMLElsaMultichoiceRecordsPropertyElement>;
            "elsa-singlechoice-records-property": LocalJSX.ElsaSinglechoiceRecordsProperty & JSXBase.HTMLAttributes<HTMLElsaSinglechoiceRecordsPropertyElement>;
        }
    }
}
