/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActivityDefinitionProperty, ActivityModel, ActivityPropertyDescriptor, IntellisenseContext } from "./models/elsa-interfaces";
import { HeActivityPropertyDescriptor, ITextProperty, NestedActivityDefinitionProperty, NestedPropertyModel } from "./models/custom-component-models";
export namespace Components {
    interface ConditionalTextListProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface CustomInputProperty {
        "context"?: string;
        "customProperty": ITextProperty;
        "editorHeight": string;
        "index": number;
        "intellisenseContext": IntellisenseContext;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "showLabel": boolean;
        "singleLineMode": boolean;
        "supportedSyntaxes": Array<string>;
    }
    interface CustomTextProperty {
        "activityModel": ActivityModel;
        "editorHeight": string;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
        "singleLine": boolean;
    }
    interface HeCheckListProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeCheckboxOptionsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeCheckboxProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeJsonProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeMultiLineProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeMultiTextProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HePotscoreRadioOptionsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeRadioOptionsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeSingleLineProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeSwitchOptionsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeTextActivityProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeWeightedCheckboxOptionGroupProperty {
        "activityModel": ActivityModel;
        "propertyModel": NestedActivityDefinitionProperty;
    }
    interface HeWeightedCheckboxProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface HeWeightedRadioOptionGroupProperty {
        "activityModel": ActivityModel;
        "propertyModel": NestedActivityDefinitionProperty;
    }
    interface HeWeightedRadioProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
    interface QuestionProperty {
        "activityModel": ActivityModel;
        "questionModel": NestedPropertyModel;
    }
    interface QuestionScreenProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
        "questionProperties": Array<HeActivityPropertyDescriptor>;
    }
    interface SwitchOptionsProperty {
        "activityModel": ActivityModel;
        "propertyDescriptor": ActivityPropertyDescriptor;
        "propertyModel": ActivityDefinitionProperty;
    }
}
export interface CustomInputPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCustomInputPropertyElement;
}
export interface HeCheckListPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeCheckListPropertyElement;
}
export interface HeCheckboxOptionsPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeCheckboxOptionsPropertyElement;
}
export interface HeCheckboxPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeCheckboxPropertyElement;
}
export interface HeJsonPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeJsonPropertyElement;
}
export interface HeMultiLinePropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeMultiLinePropertyElement;
}
export interface HeMultiTextPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeMultiTextPropertyElement;
}
export interface HePotscoreRadioOptionsPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHePotscoreRadioOptionsPropertyElement;
}
export interface HeRadioOptionsPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeRadioOptionsPropertyElement;
}
export interface HeSingleLinePropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeSingleLinePropertyElement;
}
export interface HeSwitchOptionsPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeSwitchOptionsPropertyElement;
}
export interface HeTextActivityPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeTextActivityPropertyElement;
}
export interface HeWeightedCheckboxOptionGroupPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeWeightedCheckboxOptionGroupPropertyElement;
}
export interface HeWeightedCheckboxPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeWeightedCheckboxPropertyElement;
}
export interface HeWeightedRadioOptionGroupPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeWeightedRadioOptionGroupPropertyElement;
}
export interface HeWeightedRadioPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHeWeightedRadioPropertyElement;
}
export interface QuestionPropertyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLQuestionPropertyElement;
}
declare global {
    interface HTMLConditionalTextListPropertyElement extends Components.ConditionalTextListProperty, HTMLStencilElement {
    }
    var HTMLConditionalTextListPropertyElement: {
        prototype: HTMLConditionalTextListPropertyElement;
        new (): HTMLConditionalTextListPropertyElement;
    };
    interface HTMLCustomInputPropertyElement extends Components.CustomInputProperty, HTMLStencilElement {
    }
    var HTMLCustomInputPropertyElement: {
        prototype: HTMLCustomInputPropertyElement;
        new (): HTMLCustomInputPropertyElement;
    };
    interface HTMLCustomTextPropertyElement extends Components.CustomTextProperty, HTMLStencilElement {
    }
    var HTMLCustomTextPropertyElement: {
        prototype: HTMLCustomTextPropertyElement;
        new (): HTMLCustomTextPropertyElement;
    };
    interface HTMLHeCheckListPropertyElement extends Components.HeCheckListProperty, HTMLStencilElement {
    }
    var HTMLHeCheckListPropertyElement: {
        prototype: HTMLHeCheckListPropertyElement;
        new (): HTMLHeCheckListPropertyElement;
    };
    interface HTMLHeCheckboxOptionsPropertyElement extends Components.HeCheckboxOptionsProperty, HTMLStencilElement {
    }
    var HTMLHeCheckboxOptionsPropertyElement: {
        prototype: HTMLHeCheckboxOptionsPropertyElement;
        new (): HTMLHeCheckboxOptionsPropertyElement;
    };
    interface HTMLHeCheckboxPropertyElement extends Components.HeCheckboxProperty, HTMLStencilElement {
    }
    var HTMLHeCheckboxPropertyElement: {
        prototype: HTMLHeCheckboxPropertyElement;
        new (): HTMLHeCheckboxPropertyElement;
    };
    interface HTMLHeJsonPropertyElement extends Components.HeJsonProperty, HTMLStencilElement {
    }
    var HTMLHeJsonPropertyElement: {
        prototype: HTMLHeJsonPropertyElement;
        new (): HTMLHeJsonPropertyElement;
    };
    interface HTMLHeMultiLinePropertyElement extends Components.HeMultiLineProperty, HTMLStencilElement {
    }
    var HTMLHeMultiLinePropertyElement: {
        prototype: HTMLHeMultiLinePropertyElement;
        new (): HTMLHeMultiLinePropertyElement;
    };
    interface HTMLHeMultiTextPropertyElement extends Components.HeMultiTextProperty, HTMLStencilElement {
    }
    var HTMLHeMultiTextPropertyElement: {
        prototype: HTMLHeMultiTextPropertyElement;
        new (): HTMLHeMultiTextPropertyElement;
    };
    interface HTMLHePotscoreRadioOptionsPropertyElement extends Components.HePotscoreRadioOptionsProperty, HTMLStencilElement {
    }
    var HTMLHePotscoreRadioOptionsPropertyElement: {
        prototype: HTMLHePotscoreRadioOptionsPropertyElement;
        new (): HTMLHePotscoreRadioOptionsPropertyElement;
    };
    interface HTMLHeRadioOptionsPropertyElement extends Components.HeRadioOptionsProperty, HTMLStencilElement {
    }
    var HTMLHeRadioOptionsPropertyElement: {
        prototype: HTMLHeRadioOptionsPropertyElement;
        new (): HTMLHeRadioOptionsPropertyElement;
    };
    interface HTMLHeSingleLinePropertyElement extends Components.HeSingleLineProperty, HTMLStencilElement {
    }
    var HTMLHeSingleLinePropertyElement: {
        prototype: HTMLHeSingleLinePropertyElement;
        new (): HTMLHeSingleLinePropertyElement;
    };
    interface HTMLHeSwitchOptionsPropertyElement extends Components.HeSwitchOptionsProperty, HTMLStencilElement {
    }
    var HTMLHeSwitchOptionsPropertyElement: {
        prototype: HTMLHeSwitchOptionsPropertyElement;
        new (): HTMLHeSwitchOptionsPropertyElement;
    };
    interface HTMLHeTextActivityPropertyElement extends Components.HeTextActivityProperty, HTMLStencilElement {
    }
    var HTMLHeTextActivityPropertyElement: {
        prototype: HTMLHeTextActivityPropertyElement;
        new (): HTMLHeTextActivityPropertyElement;
    };
    interface HTMLHeWeightedCheckboxOptionGroupPropertyElement extends Components.HeWeightedCheckboxOptionGroupProperty, HTMLStencilElement {
    }
    var HTMLHeWeightedCheckboxOptionGroupPropertyElement: {
        prototype: HTMLHeWeightedCheckboxOptionGroupPropertyElement;
        new (): HTMLHeWeightedCheckboxOptionGroupPropertyElement;
    };
    interface HTMLHeWeightedCheckboxPropertyElement extends Components.HeWeightedCheckboxProperty, HTMLStencilElement {
    }
    var HTMLHeWeightedCheckboxPropertyElement: {
        prototype: HTMLHeWeightedCheckboxPropertyElement;
        new (): HTMLHeWeightedCheckboxPropertyElement;
    };
    interface HTMLHeWeightedRadioOptionGroupPropertyElement extends Components.HeWeightedRadioOptionGroupProperty, HTMLStencilElement {
    }
    var HTMLHeWeightedRadioOptionGroupPropertyElement: {
        prototype: HTMLHeWeightedRadioOptionGroupPropertyElement;
        new (): HTMLHeWeightedRadioOptionGroupPropertyElement;
    };
    interface HTMLHeWeightedRadioPropertyElement extends Components.HeWeightedRadioProperty, HTMLStencilElement {
    }
    var HTMLHeWeightedRadioPropertyElement: {
        prototype: HTMLHeWeightedRadioPropertyElement;
        new (): HTMLHeWeightedRadioPropertyElement;
    };
    interface HTMLQuestionPropertyElement extends Components.QuestionProperty, HTMLStencilElement {
    }
    var HTMLQuestionPropertyElement: {
        prototype: HTMLQuestionPropertyElement;
        new (): HTMLQuestionPropertyElement;
    };
    interface HTMLQuestionScreenPropertyElement extends Components.QuestionScreenProperty, HTMLStencilElement {
    }
    var HTMLQuestionScreenPropertyElement: {
        prototype: HTMLQuestionScreenPropertyElement;
        new (): HTMLQuestionScreenPropertyElement;
    };
    interface HTMLSwitchOptionsPropertyElement extends Components.SwitchOptionsProperty, HTMLStencilElement {
    }
    var HTMLSwitchOptionsPropertyElement: {
        prototype: HTMLSwitchOptionsPropertyElement;
        new (): HTMLSwitchOptionsPropertyElement;
    };
    interface HTMLElementTagNameMap {
        "conditional-text-list-property": HTMLConditionalTextListPropertyElement;
        "custom-input-property": HTMLCustomInputPropertyElement;
        "custom-text-property": HTMLCustomTextPropertyElement;
        "he-check-list-property": HTMLHeCheckListPropertyElement;
        "he-checkbox-options-property": HTMLHeCheckboxOptionsPropertyElement;
        "he-checkbox-property": HTMLHeCheckboxPropertyElement;
        "he-json-property": HTMLHeJsonPropertyElement;
        "he-multi-line-property": HTMLHeMultiLinePropertyElement;
        "he-multi-text-property": HTMLHeMultiTextPropertyElement;
        "he-potscore-radio-options-property": HTMLHePotscoreRadioOptionsPropertyElement;
        "he-radio-options-property": HTMLHeRadioOptionsPropertyElement;
        "he-single-line-property": HTMLHeSingleLinePropertyElement;
        "he-switch-options-property": HTMLHeSwitchOptionsPropertyElement;
        "he-text-activity-property": HTMLHeTextActivityPropertyElement;
        "he-weighted-checkbox-option-group-property": HTMLHeWeightedCheckboxOptionGroupPropertyElement;
        "he-weighted-checkbox-property": HTMLHeWeightedCheckboxPropertyElement;
        "he-weighted-radio-option-group-property": HTMLHeWeightedRadioOptionGroupPropertyElement;
        "he-weighted-radio-property": HTMLHeWeightedRadioPropertyElement;
        "question-property": HTMLQuestionPropertyElement;
        "question-screen-property": HTMLQuestionScreenPropertyElement;
        "switch-options-property": HTMLSwitchOptionsPropertyElement;
    }
}
declare namespace LocalJSX {
    interface ConditionalTextListProperty {
        "activityModel"?: ActivityModel;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface CustomInputProperty {
        "context"?: string;
        "customProperty"?: ITextProperty;
        "editorHeight"?: string;
        "index"?: number;
        "intellisenseContext"?: IntellisenseContext;
        "onValueChanged"?: (event: CustomInputPropertyCustomEvent<ITextProperty>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "showLabel"?: boolean;
        "singleLineMode"?: boolean;
        "supportedSyntaxes"?: Array<string>;
    }
    interface CustomTextProperty {
        "activityModel"?: ActivityModel;
        "editorHeight"?: string;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
        "singleLine"?: boolean;
    }
    interface HeCheckListProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeCheckListPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeCheckboxOptionsProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeCheckboxOptionsPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeCheckboxProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeCheckboxPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeJsonProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeJsonPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeMultiLineProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeMultiLinePropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeMultiTextProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeMultiTextPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HePotscoreRadioOptionsProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HePotscoreRadioOptionsPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeRadioOptionsProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeRadioOptionsPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeSingleLineProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeSingleLinePropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeSwitchOptionsProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeSwitchOptionsPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeTextActivityProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeTextActivityPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeWeightedCheckboxOptionGroupProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeWeightedCheckboxOptionGroupPropertyCustomEvent<string>) => void;
        "propertyModel"?: NestedActivityDefinitionProperty;
    }
    interface HeWeightedCheckboxProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeWeightedCheckboxPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface HeWeightedRadioOptionGroupProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeWeightedRadioOptionGroupPropertyCustomEvent<string>) => void;
        "propertyModel"?: NestedActivityDefinitionProperty;
    }
    interface HeWeightedRadioProperty {
        "activityModel"?: ActivityModel;
        "onExpressionChanged"?: (event: HeWeightedRadioPropertyCustomEvent<string>) => void;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface QuestionProperty {
        "activityModel"?: ActivityModel;
        "onUpdateQuestionScreen"?: (event: QuestionPropertyCustomEvent<string>) => void;
        "questionModel"?: NestedPropertyModel;
    }
    interface QuestionScreenProperty {
        "activityModel"?: ActivityModel;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
        "questionProperties"?: Array<HeActivityPropertyDescriptor>;
    }
    interface SwitchOptionsProperty {
        "activityModel"?: ActivityModel;
        "propertyDescriptor"?: ActivityPropertyDescriptor;
        "propertyModel"?: ActivityDefinitionProperty;
    }
    interface IntrinsicElements {
        "conditional-text-list-property": ConditionalTextListProperty;
        "custom-input-property": CustomInputProperty;
        "custom-text-property": CustomTextProperty;
        "he-check-list-property": HeCheckListProperty;
        "he-checkbox-options-property": HeCheckboxOptionsProperty;
        "he-checkbox-property": HeCheckboxProperty;
        "he-json-property": HeJsonProperty;
        "he-multi-line-property": HeMultiLineProperty;
        "he-multi-text-property": HeMultiTextProperty;
        "he-potscore-radio-options-property": HePotscoreRadioOptionsProperty;
        "he-radio-options-property": HeRadioOptionsProperty;
        "he-single-line-property": HeSingleLineProperty;
        "he-switch-options-property": HeSwitchOptionsProperty;
        "he-text-activity-property": HeTextActivityProperty;
        "he-weighted-checkbox-option-group-property": HeWeightedCheckboxOptionGroupProperty;
        "he-weighted-checkbox-property": HeWeightedCheckboxProperty;
        "he-weighted-radio-option-group-property": HeWeightedRadioOptionGroupProperty;
        "he-weighted-radio-property": HeWeightedRadioProperty;
        "question-property": QuestionProperty;
        "question-screen-property": QuestionScreenProperty;
        "switch-options-property": SwitchOptionsProperty;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "conditional-text-list-property": LocalJSX.ConditionalTextListProperty & JSXBase.HTMLAttributes<HTMLConditionalTextListPropertyElement>;
            "custom-input-property": LocalJSX.CustomInputProperty & JSXBase.HTMLAttributes<HTMLCustomInputPropertyElement>;
            "custom-text-property": LocalJSX.CustomTextProperty & JSXBase.HTMLAttributes<HTMLCustomTextPropertyElement>;
            "he-check-list-property": LocalJSX.HeCheckListProperty & JSXBase.HTMLAttributes<HTMLHeCheckListPropertyElement>;
            "he-checkbox-options-property": LocalJSX.HeCheckboxOptionsProperty & JSXBase.HTMLAttributes<HTMLHeCheckboxOptionsPropertyElement>;
            "he-checkbox-property": LocalJSX.HeCheckboxProperty & JSXBase.HTMLAttributes<HTMLHeCheckboxPropertyElement>;
            "he-json-property": LocalJSX.HeJsonProperty & JSXBase.HTMLAttributes<HTMLHeJsonPropertyElement>;
            "he-multi-line-property": LocalJSX.HeMultiLineProperty & JSXBase.HTMLAttributes<HTMLHeMultiLinePropertyElement>;
            "he-multi-text-property": LocalJSX.HeMultiTextProperty & JSXBase.HTMLAttributes<HTMLHeMultiTextPropertyElement>;
            "he-potscore-radio-options-property": LocalJSX.HePotscoreRadioOptionsProperty & JSXBase.HTMLAttributes<HTMLHePotscoreRadioOptionsPropertyElement>;
            "he-radio-options-property": LocalJSX.HeRadioOptionsProperty & JSXBase.HTMLAttributes<HTMLHeRadioOptionsPropertyElement>;
            "he-single-line-property": LocalJSX.HeSingleLineProperty & JSXBase.HTMLAttributes<HTMLHeSingleLinePropertyElement>;
            "he-switch-options-property": LocalJSX.HeSwitchOptionsProperty & JSXBase.HTMLAttributes<HTMLHeSwitchOptionsPropertyElement>;
            "he-text-activity-property": LocalJSX.HeTextActivityProperty & JSXBase.HTMLAttributes<HTMLHeTextActivityPropertyElement>;
            "he-weighted-checkbox-option-group-property": LocalJSX.HeWeightedCheckboxOptionGroupProperty & JSXBase.HTMLAttributes<HTMLHeWeightedCheckboxOptionGroupPropertyElement>;
            "he-weighted-checkbox-property": LocalJSX.HeWeightedCheckboxProperty & JSXBase.HTMLAttributes<HTMLHeWeightedCheckboxPropertyElement>;
            "he-weighted-radio-option-group-property": LocalJSX.HeWeightedRadioOptionGroupProperty & JSXBase.HTMLAttributes<HTMLHeWeightedRadioOptionGroupPropertyElement>;
            "he-weighted-radio-property": LocalJSX.HeWeightedRadioProperty & JSXBase.HTMLAttributes<HTMLHeWeightedRadioPropertyElement>;
            "question-property": LocalJSX.QuestionProperty & JSXBase.HTMLAttributes<HTMLQuestionPropertyElement>;
            "question-screen-property": LocalJSX.QuestionScreenProperty & JSXBase.HTMLAttributes<HTMLQuestionScreenPropertyElement>;
            "switch-options-property": LocalJSX.SwitchOptionsProperty & JSXBase.HTMLAttributes<HTMLSwitchOptionsPropertyElement>;
        }
    }
}
